### ISSUE TITLE
Request for default username & password 

### ISSUE THREAD

**Issue by fdagreat** [prolinkinfo/RealEstateCRM#1]
I need to view the website with the link shared on the repo https://real-estate-crm-jet.vercel.app/ 
but you did not provide default username and password for people to test it out. please provide them.

**Comment by prolinkinfo** [comment]
@fdagreat. Thanks for the suggestion.

Here are the credentials and also mentioned on the Readme.

**Admin access:** 

Username: admin@gmail.com
Password: admin123

**Regular access:**

Username: user@gmail.com
Password: user123

**Comment by fdagreat** [comment]
Thank you I was able to login.
